// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4Rb8QEUuFikPbPWVtcLqVNl-a6d4R9G4',
    appId: '1:994982793397:web:f777b8559a0cfa44acaefc',
    messagingSenderId: '994982793397',
    projectId: 'todo-app-40801',
    authDomain: 'todo-app-40801.firebaseapp.com',
    storageBucket: 'todo-app-40801.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjN6N6UEaInzVqAGnk-5fHv-Xq2PhwaF4',
    appId: '1:994982793397:android:333089b96860a810acaefc',
    messagingSenderId: '994982793397',
    projectId: 'todo-app-40801',
    storageBucket: 'todo-app-40801.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3FySfHVJreV4nVBeqzjhPHROOLLWij5c',
    appId: '1:994982793397:ios:0b56218a53f19200acaefc',
    messagingSenderId: '994982793397',
    projectId: 'todo-app-40801',
    storageBucket: 'todo-app-40801.appspot.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3FySfHVJreV4nVBeqzjhPHROOLLWij5c',
    appId: '1:994982793397:ios:09d2317364678fe6acaefc',
    messagingSenderId: '994982793397',
    projectId: 'todo-app-40801',
    storageBucket: 'todo-app-40801.appspot.com',
    iosBundleId: 'com.example.todoApp.RunnerTests',
  );
}
